# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waterquality.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12waterquality.proto\"=\n\x07Quality\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\n\n\x02ph\x18\x03 \x01(\x02\"M\n\nPredictReq\x12\x1b\n\tqualities\x18\x01 \x03(\x0b\x32\x08.Quality\x12\x11\n\tlook_back\x18\x02 \x01(\x03\x12\x0f\n\x07horizon\x18\x03 \x01(\x03\"*\n\x0bPredictResp\x12\x1b\n\tqualities\x18\x01 \x03(\x0b\x32\x08.Quality\"\x1f\n\x0eGuessLevelResp\x12\r\n\x05level\x18\x01 \x01(\x03\x32h\n\x13WaterQualityService\x12&\n\x07Predict\x12\x0b.PredictReq\x1a\x0c.PredictResp\"\x00\x12)\n\nGuessLevel\x12\x08.Quality\x1a\x0f.GuessLevelResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waterquality_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUALITY']._serialized_start=22
  _globals['_QUALITY']._serialized_end=83
  _globals['_PREDICTREQ']._serialized_start=85
  _globals['_PREDICTREQ']._serialized_end=162
  _globals['_PREDICTRESP']._serialized_start=164
  _globals['_PREDICTRESP']._serialized_end=206
  _globals['_GUESSLEVELRESP']._serialized_start=208
  _globals['_GUESSLEVELRESP']._serialized_end=239
  _globals['_WATERQUALITYSERVICE']._serialized_start=241
  _globals['_WATERQUALITYSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
